services:
  - type: web
    name: mailgram
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mailgram_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true